LOGIN_BUTTON_SELECTOR = '#login-button'
SHOPPING_CART_BUTTON = '#shopping_cart_container'
CHECKOUT_BUTTON = '.btn.btn_action.btn_medium.checkout_button'
FINISH_STEP_TWO = '#finish'
BACK_HOME = '#back-to-products'
BACKPACK_BUTTON_SELECTOR = 'add-to-cart-sauce-labs-backpack'
BIKE_LIGHT_BUTTON_SELECTOR = 'add-to-cart-sauce-labs-bike-light'
